### ISSUE TITLE
Authentication does not work

### ISSUE THREAD

**Issue by jakeleventhal** [XeroAPI/node-oauth2-example#1]
I updated the config.json with the client id and secret key from my application and when i click the connect link, it takes me to this error page
<img width="632" alt="Screen Shot 2019-09-22 at 4 23 28 PM" src="https://user-images.githubusercontent.com/15133828/65395899-69e3b480-dd55-11e9-9a62-d25a53fe4e36.png">

at the following url
https://login.xero.com/identity/error?errorId=CfDJ8AUeo1ra0O5KpNg5WAp_2WIt8ZTXjOlMAOZNbETePcDvxtaLQNPyWBKsbZy2-FE7Y-oXG7forWC64_ahhKcj86uWhlAsMJatpBBfRWPoBwaVmDLQe3WiIEJuXot1K7J6S8X2UlNcKxRpo2tK1jblH4C4_gehTRL6fw9ZMfLiEc6eITuVF-UCQan9ten3m4W-7H0hEac5yXJSMg8_qQlS5QrcjNquuFM-JFVph1UUJX0xsjzlsZ6y8agUslmyxCILXHsAGjFRzCWz-QEiCLcLRz4rW6w0lMigyQ2xNXnAggyyuPlkSZYjq03kGT7Muxl57w

**Comment by SerKnight** [comment]
Hi @jakeleventhal - just getting to this.

What you are likely looking for is the SDK sample app: https://github.com/XeroAPI/xero-node-oauth2-app

This was just to show devs who preferred to not use a Javascript SDK (api wrapper)
