### ISSUE TITLE
Example using node module

### ISSUE THREAD

**Issue by jakeleventhal** [XeroAPI/node-oauth2-example#2]
There is no example of oauth 2 using the `xero-node` module

**Comment by SerKnight** [comment]
Hi @jakeleventhal  - this repo was for JS devs who wanted an example of how to connect to Xero's API without the SDK.

However as the maintainer of the xero-node project, i'd highly recommend it :)

You can checkout that very robust sample app here: https://github.com/XeroAPI/xero-node-oauth2-app
