### ISSUE TITLE
client.authorizationCallback() is now just client.callback()

### ISSUE THREAD

**Issue by wildhart** [XeroAPI/node-oauth2-example#3]
This line doesn't work:

https://github.com/XeroAPI/node-oauth2-example/blob/9ad38a872d3a2515c2646226d0b4ad0a4d68bc17/index.js#L68

The correct method for openid-client@3.15.1 is now [`client.callback()`](https://github.com/panva/node-openid-client/blob/master/docs/README.md#clientcallbackredirecturi-parameters-checks-extras) which I have confirmed works.

**Comment by SerKnight** [comment]
Hi @wildhart - apologies on not updating this project. Its been swapped for a much fuller sample app implementation which you can find here: https://github.com/XeroAPI/xero-node-oauth2-app

**Comment by wildhart** [comment]
Thanks @SerKnight.  Might be worth mentioning this at the top your readme ;-)

**Comment by SerKnight** [comment]
Yes - just got repo rights - will do that!
